### ISSUE TITLE
Game support implementation

### ISSUE THREAD

**Issue by VictorVow** [dulsi/libgamerzilla#1]
From [your article](https://www.gamingonlinux.com/2020/12/open-source-game-achievements-with-gamerzilla) it sounds like games have to specifically implement support for Gamerzilla, which doesn't sound to me like the best route for widespread compatibility. 

Platforms like Steam, Origin, Epic Games etc all support achievements, which seems to me like it's not implemented at a per-game level. Game sees you complete a task, sends a trigger that you've got an achievement, then the platform you're using records an achievement to your profile. 

Can't Gamerzilla use the same triggers all these other platforms are using instead of requiring individual game support?

**Comment by dulsi** [comment]
Actually each achievement system uses it's own SDK to add support to a game. If you write a game and want to support Steam, Origin and Epic Games achievements, you are coding support three times and making a separate build for each platform. That is why I think a common open source game achievement system would help game developers. (Or at least you probably are making multiple builds. You might be able to write a layer that handles the difference but I don't think most people do.)

So I can't just tap into what other platforms are using. Additionally the other platforms do not specify all the achievements information in the game. When you upload your game to Steam, you specify all the achievement information. The game only needs to know that event X gives achievement Y. The name/description of the achievement is not needed in the game. (Games might have the information if they have an achievement screen but none of the calls to the Steam SDK send that information.)

LibGamerzilla could have a version that automatically forward to Steam as well. But I'm not interested in doing that work.
