### ISSUE TITLE
Segfault on passing an empty (but initialized) Gamerzilla to GamerzillaSetGame

### ISSUE THREAD

**Issue by Houkime** [dulsi/libgamerzilla#3]
`strdup()` causes undefined behaviour when passed NULL instead of a valid string.
https://stackoverflow.com/questions/6432384/strdup-dumping-core-on-passing-null

Possible mitigations:
* Allow `GamerzillaSetGame()` to fail (needs API change).
* Allow `current` to have some fields NULL (do not call strdup on NULL).
* Convert NULLs to empty strings for storage in current.
* Use empty strings in Gamerzilla initializer (partial solution).

**Comment by Houkime** [comment]
strdup() causes undefined behaviour when passed NULL instead of valid strings.

**Comment by dulsi** [comment]
GamerzillaSetGame now returns -1 if it fails.
